### ISSUE TITLE
Metadata homepage does not exist

### ISSUE THREAD

**Issue by luipir** [TomasdelaBarra/QTRANUS#10]
please fix homepage in metadata.. it does not exist and it's necessary

**Comment by pcav** [comment]
homepage is not mandatory, but highly appreciated. If nothing more specific, you can use this repo link.
Thanks.

**Comment by luipir** [comment]
not mandatory bu should have (if set) a reliable value

**Comment by yanezlb** [comment]
Corrected parameter
