### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [TomasdelaBarra/QTRANUS#8]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by yanezlb** [comment]
We remove all unnecessary files.
Thanks.

**Comment by pcav** [comment]
Still there. Please do not close a ticket unless resolved.
Thanks.

**Comment by yanezlb** [comment]
Ok,
   What other files we should remove?
Thanks for your help.

**Comment by yanezlb** [comment]
We remove all unnecessary files. 
.pyc, .sh and test folder 
Thanks.
